### ISSUE TITLE
Sign User's Keys

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/hub#190]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

After verifying another user's public key, I want to sign it

### Motivation

When encrypting something using somebody's public key, one needs to be sure that this public key is authentic. In order to increase trust, we want a verification mechanism and the ability to sign public keys once verification completed. The signature can then be used at a later point to prevent accidentally granting access to some untrusted user.

```[tasklist]
### Tasks
- [x] Decide, how to verify a user's public key (prompt for some digits of its hash?)
```

**Comment by SailReal** [comment]
@overheadhunter this is implemented in https://github.com/cryptomator/hub/pull/281, so we can close this issue, right?
