### ISSUE TITLE
Deprecate `Vault Admin Password`

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/hub#209]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/hub/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/hub/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Switch back to role-based access control in access-restricted APIs

### Motivation

Since we needed a mechanism to decrypt certain vault-specific encapsulated keys in the browser, we relied on the _Vault Admin Password_. **This has now been obsoleted** by the fact that with #207 browsers are promoted to being _Devices_ which can access the user's key pair. So if said vault-specific keys are now encapsulated for authorized users, there is no need for the _Vault Admin Password_ any longer.

Among those keys were not just the vault's masterkey, but also a signing key (added in #81 and #87) for signing http requests that were only allowed to be made by vault owners (e.g. managing vault members). The backend relied on these signatures to verify whether the user is allowed to make such a request.

Since #207 re-introduces vault roles, the backend can rely on those again.

### Anything else?

We can not completely remove the _Vault Admin Password_ yet, as we need to migrate existing data first.
```[tasklist]
### Tasks
- [x] Replace `@VaultAdminOnlyFilter`
- [x] Remove _Vault Admin Password_ prompt from Hub frontend
- [x] Display "Manage Vault" button depending on role
- [ ] https://github.com/cryptomator/hub/issues/214
```
